RED (3 out of 47 tests failed) - 117ms
1) db4ounit.tests.fixtures.FixtureBasedTestSuiteTestCase.test
2) db4ounit.tests.fixtures.FixtureBasedTestSuiteTestCase.testLabel
3) db4ounit.tests.fixtures.FixtureBasedTestSuiteTestCase.testCombinationToRun

1) db4ounit.tests.fixtures.FixtureBasedTestSuiteTestCase.test: db4ounit.AssertionException: Expected 'testFoo(f11, f21)' but was 'testBar(f11, f21)'
	at db4ounit.Assert.fail(Assert.java:55)
	at db4ounit.Assert.areEqual(Assert.java:125)
	at db4ounit.Assert.areEqual(Assert.java:129)
	at db4ounit.Iterator4Assert.assertNext(Iterator4Assert.java:33)
	at db4ounit.Iterator4Assert.areEqual(Iterator4Assert.java:20)
	at db4ounit.Iterator4Assert.areEqual(Iterator4Assert.java:37)
	at db4ounit.mocking.MethodCallRecorder.verify(MethodCallRecorder.java:32)
	at db4ounit.tests.fixtures.FixtureBasedTestSuiteTestCase.test(FixtureBasedTestSuiteTestCase.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at db4ounit.TestMethod.invoke(TestMethod.java:65)
	at db4ounit.TestMethod.run(TestMethod.java:43)
	at db4ounit.ContextfulTest$3.run(ContextfulTest.java:36)
	at com.db4o.foundation.DynamicVariable.with(DynamicVariable.java:54)
	at db4ounit.fixtures.FixtureContext.run(FixtureContext.java:33)
	at db4ounit.fixtures.Contextful.run(Contextful.java:20)
	at db4ounit.ContextfulTest.run(ContextfulTest.java:34)
	at db4ounit.TestRunner.runTest(TestRunner.java:44)
	at db4ounit.TestRunner.access$000(TestRunner.java:7)
	at db4ounit.TestRunner$2.run(TestRunner.java:32)
	at com.db4o.foundation.DynamicVariable.with(DynamicVariable.java:54)
	at com.db4o.foundation.Environments.runWith(Environments.java:28)
	at db4ounit.TestRunner.run(TestRunner.java:28)
	at db4ounit.ConsoleTestRunner.run(ConsoleTestRunner.java:48)
	at db4ounit.ConsoleTestRunner.run(ConsoleTestRunner.java:37)
	at db4ounit.tests.AllTests.main(AllTests.java:28)


2) db4ounit.tests.fixtures.FixtureBasedTestSuiteTestCase.testLabel: db4ounit.AssertionException: Expected '(f2[0]) (f1[0]) db4ounit.tests.fixtures.FixtureBasedTestSuiteTestCase$TestUnit.testFoo' but was '(f2[0]) (f1[0]) db4ounit.tests.fixtures.FixtureBasedTestSuiteTestCase$TestUnit.testBar'
	at db4ounit.Assert.fail(Assert.java:55)
	at db4ounit.Assert.areEqual(Assert.java:125)
	at db4ounit.Assert.areEqual(Assert.java:129)
	at db4ounit.Iterator4Assert.assertNext(Iterator4Assert.java:33)
	at db4ounit.Iterator4Assert.areEqual(Iterator4Assert.java:20)
	at db4ounit.Iterator4Assert.areEqual(Iterator4Assert.java:37)
	at db4ounit.tests.fixtures.FixtureBasedTestSuiteTestCase.testLabel(FixtureBasedTestSuiteTestCase.java:159)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at db4ounit.TestMethod.invoke(TestMethod.java:65)
	at db4ounit.TestMethod.run(TestMethod.java:43)
	at db4ounit.ContextfulTest$3.run(ContextfulTest.java:36)
	at com.db4o.foundation.DynamicVariable.with(DynamicVariable.java:54)
	at db4ounit.fixtures.FixtureContext.run(FixtureContext.java:33)
	at db4ounit.fixtures.Contextful.run(Contextful.java:20)
	at db4ounit.ContextfulTest.run(ContextfulTest.java:34)
	at db4ounit.TestRunner.runTest(TestRunner.java:44)
	at db4ounit.TestRunner.access$000(TestRunner.java:7)
	at db4ounit.TestRunner$2.run(TestRunner.java:32)
	at com.db4o.foundation.DynamicVariable.with(DynamicVariable.java:54)
	at com.db4o.foundation.Environments.runWith(Environments.java:28)
	at db4ounit.TestRunner.run(TestRunner.java:28)
	at db4ounit.ConsoleTestRunner.run(ConsoleTestRunner.java:48)
	at db4ounit.ConsoleTestRunner.run(ConsoleTestRunner.java:37)
	at db4ounit.tests.AllTests.main(AllTests.java:28)


3) db4ounit.tests.fixtures.FixtureBasedTestSuiteTestCase.testCombinationToRun: db4ounit.AssertionException: Expected 'testFoo(f11, f22)' but was 'testBar(f11, f22)'
	at db4ounit.Assert.fail(Assert.java:55)
	at db4ounit.Assert.areEqual(Assert.java:125)
	at db4ounit.Assert.areEqual(Assert.java:129)
	at db4ounit.Iterator4Assert.assertNext(Iterator4Assert.java:33)
	at db4ounit.Iterator4Assert.areEqual(Iterator4Assert.java:20)
	at db4ounit.Iterator4Assert.areEqual(Iterator4Assert.java:37)
	at db4ounit.mocking.MethodCallRecorder.verify(MethodCallRecorder.java:32)
	at db4ounit.tests.fixtures.FixtureBasedTestSuiteTestCase.testCombinationToRun(FixtureBasedTestSuiteTestCase.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at db4ounit.TestMethod.invoke(TestMethod.java:65)
	at db4ounit.TestMethod.run(TestMethod.java:43)
	at db4ounit.ContextfulTest$3.run(ContextfulTest.java:36)
	at com.db4o.foundation.DynamicVariable.with(DynamicVariable.java:54)
	at db4ounit.fixtures.FixtureContext.run(FixtureContext.java:33)
	at db4ounit.fixtures.Contextful.run(Contextful.java:20)
	at db4ounit.ContextfulTest.run(ContextfulTest.java:34)
	at db4ounit.TestRunner.runTest(TestRunner.java:44)
	at db4ounit.TestRunner.access$000(TestRunner.java:7)
	at db4ounit.TestRunner$2.run(TestRunner.java:32)
	at com.db4o.foundation.DynamicVariable.with(DynamicVariable.java:54)
	at com.db4o.foundation.Environments.runWith(Environments.java:28)
	at db4ounit.TestRunner.run(TestRunner.java:28)
	at db4ounit.ConsoleTestRunner.run(ConsoleTestRunner.java:48)
	at db4ounit.ConsoleTestRunner.run(ConsoleTestRunner.java:37)
	at db4ounit.tests.AllTests.main(AllTests.java:28)

